BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Clients] ALTER COLUMN [lat] DECIMAL(32,16) NULL;
ALTER TABLE [dbo].[Clients] ALTER COLUMN [lng] DECIMAL(32,16) NULL;

-- AlterTable
ALTER TABLE [dbo].[Sites] ALTER COLUMN [lat] DECIMAL(32,16) NULL;
ALTER TABLE [dbo].[Sites] ALTER COLUMN [lng] DECIMAL(32,16) NULL;

-- AlterTable
ALTER TABLE [dbo].[Vendors] ALTER COLUMN [lat] DECIMAL(32,16) NULL;
ALTER TABLE [dbo].[Vendors] ALTER COLUMN [lng] DECIMAL(32,16) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
