const existingEmployees = [
  {
    businessPhones: [],
    displayName: "Aaron Johnson -",
    givenName: "Aaron",
    jobTitle: null,
    mail: "Aaron.Johnson@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Johnson",
    userPrincipalName: "Aaron.Johnson@evergreenbrands.com",
    id: "7dd19e4b-e822-42aa-aec7-bb582cfdbbb9",
  },
  {
    businessPhones: [],
    displayName: "Accounting",
    givenName: "Accounting",
    jobTitle: null,
    mail: "Accounting@Lawn-tech.net",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "Accounting@Lawn-tech.net",
    id: "01d4d52c-e1fa-4455-a805-2ff76a1acab3",
  },
  {
    businessPhones: [],
    displayName: "Adrian Melgoza",
    givenName: "Adrian",
    jobTitle: "Landscape Forman",
    mail: "AdrMel@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Melgoza",
    userPrincipalName:
      "AdrMel_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "d927cf10-d813-4bcf-9984-480401fe5585",
  },
  {
    businessPhones: [],
    displayName: "Ahmed Hesham",
    givenName: "Ahmed",
    jobTitle: "Community Association Manager",
    mail: "Ahmed.Hesham@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Hesham",
    userPrincipalName:
      "Ahmed.Hesham_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "4ec5c725-e857-4978-bda5-3abe8624bfda",
  },
  {
    businessPhones: [],
    displayName: "Aimee Wescott",
    givenName: "Aimee",
    jobTitle: null,
    mail: "Aimee.Wescott@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Wescott",
    userPrincipalName: "Aimee.Wescott@evergreenbrands.com",
    id: "e00f685b-5d71-4356-be6a-d5fd025f2722",
  },
  {
    businessPhones: ["425-449-5681 ext. 408"],
    displayName: "Alexis Bennett",
    givenName: "Alexis",
    jobTitle: "Community Association Manager",
    mail: "alexis.bennett@condoshield.org",
    mobilePhone: null,
    officeLocation: "Everett",
    preferredLanguage: "en-US",
    surname: "Bennett",
    userPrincipalName:
      "alexis.bennett_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "313f9e19-4751-4f6a-9ba9-3719a6f3cc6c",
  },
  {
    businessPhones: ["(206) 899-6273"],
    displayName: "Alison Pyles",
    givenName: "Alison",
    jobTitle: "On-Demand Channel Manager",
    mail: "AliPyl@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "Pyles",
    userPrincipalName:
      "AliPyl_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2362ff33-a06f-4219-b477-c3d02c73001e",
  },
  {
    businessPhones: ["206-797-7456"],
    displayName: "Amanda Barrigan",
    givenName: "Amanda",
    jobTitle: "Account Manager",
    mail: "AmaBar@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "Barrigan",
    userPrincipalName:
      "AmaBar_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8f934be5-c347-42b5-a7c2-74976b097fa2",
  },
  {
    businessPhones: ["(713) 282-7682"],
    displayName: "Amber Kegebein - SM 2026",
    givenName: "Amber",
    jobTitle: "Sr. Account Manager",
    mail: "AmbKeg@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Kegebein",
    userPrincipalName:
      "AmbKeg_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "18e9b69a-a85b-4756-96e0-f7cfb630287b",
  },
  {
    businessPhones: ["(206) 486-9207"],
    displayName: "Amber Morris",
    givenName: "Amber",
    jobTitle: "Sourcing Coordinator ",
    mail: "AmbMor@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Morris",
    userPrincipalName:
      "AmbMor_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3079d401-133b-43c4-9f89-0b73ac5bb2d1",
  },
  {
    businessPhones: ["(425) 981-6996"],
    displayName: "Andrew Wilson",
    givenName: "Andrew",
    jobTitle: "Sourcing Coordinator",
    mail: "AndWil@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Wilson",
    userPrincipalName:
      "AndWil_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "4dab5aaa-d684-42a1-996d-6915b66d86ba",
  },
  {
    businessPhones: [],
    displayName: "Angelina Durst",
    givenName: "Angelina",
    jobTitle: "Chief Financial Officer",
    mail: "AngDur@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Durst",
    userPrincipalName:
      "AngDur_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "d87f81eb-dad6-4909-a3b6-eb6927cefc13",
  },
  {
    businessPhones: [],
    displayName: "Angi Durst",
    givenName: "Angi",
    jobTitle: "Chief Financial Officer",
    mail: "Angi.Durst@evergreenbrands.com",
    mobilePhone: "425-681-5234",
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Durst",
    userPrincipalName: "Angi.Durst@evergreenbrands.com",
    id: "6b7e5294-9108-43e1-be36-99e7e1546c7b",
  },
  {
    businessPhones: [],
    displayName: "Anthony Fiorenza",
    givenName: "Anthony",
    jobTitle: "Crew Foreman ",
    mail: "AntFio@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Fiorenza",
    userPrincipalName:
      "AntFio_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "95392e28-032e-46b5-bad7-d6b3ef18c60a",
  },
  {
    businessPhones: [],
    displayName: "Anugrah Pandey",
    givenName: "Anugrah",
    jobTitle: "Sales Assistant",
    mail: "AnuPan@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Pandey",
    userPrincipalName:
      "AnuPan_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "e1ed8e6b-238c-40c6-bec7-31e6d58b1d9c",
  },
  {
    businessPhones: ["206-608-4722"],
    displayName: "Barb Erni",
    givenName: "Barb",
    jobTitle: "Vice President",
    mail: "BarErn@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Erni",
    userPrincipalName:
      "BarErn_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "36c0a7e4-8d98-4bed-8257-d4a00fd730eb",
  },
  {
    businessPhones: [],
    displayName: "Brady Backstrom - SM- 2023",
    givenName: "Brady",
    jobTitle: null,
    mail: "Brady@mbridge.global",
    mobilePhone: null,
    officeLocation: "Home Office",
    preferredLanguage: null,
    surname: "Backstrom",
    userPrincipalName: "Brady@mbridge.global",
    id: "56696b2b-6ef2-4c9a-bb8b-a35344f44b3c",
  },
  {
    businessPhones: [],
    displayName: "Brad Pyles",
    givenName: "Brad",
    jobTitle: "Sourcing Specialist",
    mail: "BraPyl@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Pyles",
    userPrincipalName:
      "BraPyl_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3a38722c-89f4-4027-9ac8-212ac87635da",
  },
  {
    businessPhones: ["(425) 310-8394"],
    displayName: "Bret Boggs - SM 2024",
    givenName: "Bret",
    jobTitle: null,
    mail: "Bret@wcgpro.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: null,
    surname: "Boggs",
    userPrincipalName: "Bret@wcgpro.com",
    id: "17608d6e-aa3e-41d3-9ec8-add60ded7598",
  },
  {
    businessPhones: [],
    displayName: "Breanna Warren - SM 2026",
    givenName: "Breanna",
    jobTitle: "Sourcing Coordinator",
    mail: "BreWar@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Warren",
    userPrincipalName:
      "BreWar_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3347a2b1-a695-4352-9442-d5f0a1d3fc7c",
  },
  {
    businessPhones: [],
    displayName: "Cam Abella",
    givenName: "Cam",
    jobTitle: "Assistant Community Manager ",
    mail: "Cam.Abella@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Abella",
    userPrincipalName:
      "Cam.Abella_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2a4fbf45-470c-46f1-9b2d-0c28c883df95",
  },
  {
    businessPhones: ["206-804-9919"],
    displayName: "Cathleen Turner - SM 2024",
    givenName: "Cathleen",
    jobTitle: "Paralegal",
    mail: "Cathleen.Turner@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Turner",
    userPrincipalName: "Cathleen.Turner@evergreenbrands.com",
    id: "4610fb7a-315b-4250-8c48-6b6b26348ccb",
  },
  {
    businessPhones: ["206-610-4804"],
    displayName: "Chris Butler",
    givenName: "Chris",
    jobTitle: "Senior in-house Council",
    mail: "cbb@evergreenbrands.com",
    mobilePhone: "111-111-1111",
    officeLocation: null,
    preferredLanguage: null,
    surname: "Butler",
    userPrincipalName: "cbb@evergreenbrands.com",
    id: "f8ab6c35-89c5-4f38-bb61-70c53a2bbd06",
  },
  {
    businessPhones: [],
    displayName: "Cheryl Schlittenhard",
    givenName: "Cheryl",
    jobTitle: "Accounting Specialist",
    mail: "CheSch@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Schlittenhard",
    userPrincipalName:
      "CheSch_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "409fc948-11ca-4304-a551-91ca84ce574f",
  },
  {
    businessPhones: [],
    displayName: "Connie Becerra",
    givenName: "Connie",
    jobTitle: "Intake Specialist ",
    mail: "ConBec@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Becerra",
    userPrincipalName:
      "ConBec_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2e085840-65ca-426a-84e8-fde81e16e960",
  },
  {
    businessPhones: [],
    displayName: "Corrie Ash",
    givenName: "Corrie",
    jobTitle: "Executive Assistant",
    mail: "Corrie.Ash@evergreenbrands.com",
    mobilePhone: "425-239-7839",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Ash",
    userPrincipalName: "Corrie.Ash@evergreenbrands.com",
    id: "270a7f43-f665-47a8-aa06-d7d358a866d4",
  },
  {
    businessPhones: ["(713) 482-9361"],
    displayName: "Crissa Morris - SM 2026",
    givenName: "Crissa",
    jobTitle: "On Demand Manager ",
    mail: "CriMor@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WHF",
    preferredLanguage: "en-US",
    surname: "Morris",
    userPrincipalName:
      "CriMor_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "01ae8c28-3444-453f-adf2-b059dc331fd8",
  },
  {
    businessPhones: [],
    displayName: "Dante Damiani",
    givenName: "Dante",
    jobTitle: "HR/Payroll Manager",
    mail: "DanDam@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Damiani",
    userPrincipalName:
      "DanDam_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "36524699-c3c3-493a-9843-8b79bf7df707",
  },
  {
    businessPhones: [],
    displayName: "Dante Damiani",
    givenName: "Dante",
    jobTitle: "Director of Human Resources",
    mail: "Dante.Damiani@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: null,
    surname: "Damiani",
    userPrincipalName: "Dante.Damiani@evergreenbrands.com",
    id: "103b1e33-1948-4fae-aca7-22fd98046fef",
  },
  {
    businessPhones: [],
    displayName: "Daphne Molina",
    givenName: "Daphne",
    jobTitle: "Senior Accountant",
    mail: "Daphne.Molina@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Molina",
    userPrincipalName:
      "Daphne.Molina_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "e9dadb1e-0c13-4760-9eca-a9e8fc6c8911",
  },
  {
    businessPhones: ["(617) 251-2720"],
    displayName: "Dave Wescott",
    givenName: "Dave",
    jobTitle: "CEO",
    mail: "Dave.Wescott@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Wescott",
    userPrincipalName: "Dave.Wescott@evergreenbrands.com",
    id: "39d75096-fd2e-473d-852b-1378e6f9f3d7",
  },
  {
    businessPhones: [],
    displayName: "Dave Wescott - H4H",
    givenName: "Dave",
    jobTitle: null,
    mail: "dave@Honey4hope.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Wescott",
    userPrincipalName: "dave@Honey4hope.org",
    id: "49f5b1a7-8ffc-4a44-a39a-c0d9f9a13e6b",
  },
  {
    businessPhones: [],
    displayName: "Dave Wescott - SherpaCEO",
    givenName: "Dave",
    jobTitle: null,
    mail: "Davew@sherpaceo.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Wescott",
    userPrincipalName: "Davew@sherpaceo.com",
    id: "4ed49d6c-d9a8-4a6f-8bc5-a77db182bf25",
  },
  {
    businessPhones: ["206-750-6832"],
    displayName: "David Vetter - SM 2025",
    givenName: "David",
    jobTitle: "Senior Vice President, Operations",
    mail: "David.Vetter@evergreenbrands.com",
    mobilePhone: "425-765-2253",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Vetter",
    userPrincipalName: "David.Vetter@evergreenbrands.com",
    id: "94c73eb7-a7c1-4189-8f77-b52e70918440",
  },
  {
    businessPhones: [],
    displayName: "David Lundquist",
    givenName: "David",
    jobTitle: "Director",
    mail: "David@mbridge.global",
    mobilePhone: "(425) 773-6809",
    officeLocation: "Home",
    preferredLanguage: null,
    surname: "Lundquist",
    userPrincipalName: "David@mbridge.global",
    id: "e6a24999-27c0-405f-8c61-bb4f09a61a9e",
  },
  {
    businessPhones: ["(206) 608-3085"],
    displayName: "Deanna Martin",
    givenName: "Deanna",
    jobTitle: "Sr. Account Manager ",
    mail: "DeaMar@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Home",
    preferredLanguage: "en-US",
    surname: "Martin",
    userPrincipalName:
      "DeaMar_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "9b8eb974-6328-45c3-afed-1b12bb194a0b",
  },
  {
    businessPhones: [],
    displayName: "Deanna Maguire",
    givenName: "Deanna",
    jobTitle: "Executive Assistant",
    mail: "DeannaM@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Maguire",
    userPrincipalName:
      "DeannaM_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "ac1ce265-e8ea-47b0-b12b-248cfcfd365f",
  },
  {
    businessPhones: [],
    displayName: "Deborah Gerber",
    givenName: "Deborah",
    jobTitle: null,
    mail: "debger@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Gerber",
    userPrincipalName:
      "debger_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "c9473869-baee-4f93-95e4-1aa042de61b6",
  },
  {
    businessPhones: [],
    displayName: "Diana Martin - SM 2025",
    givenName: "Diana",
    jobTitle: "CFO",
    mail: "Diana.Martin@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Martin",
    userPrincipalName: "Diana.Martin@evergreenbrands.com",
    id: "67b30408-127d-4c45-9a0c-f1e7c9d87ae1",
  },
  {
    businessPhones: [],
    displayName: "Domain Admin",
    givenName: "Domain",
    jobTitle: null,
    mail: "Domainadmin@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Admin",
    userPrincipalName: "Domainadmin@evergreenbrands.com",
    id: "16ed9334-9bef-4949-acc8-dbc605af6ebe",
  },
  {
    businessPhones: ["(206) 823-6433"],
    displayName: "Donald Anderson - SM - 2024",
    givenName: "Donald",
    jobTitle: "Director, Marketing and Revenue",
    mail: "donald.anderson@evergreenbrands.com",
    mobilePhone: "(510) 299-1786",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Anderson",
    userPrincipalName: "donald.anderson@evergreenbrands.com",
    id: "43521561-6803-4eff-b1c2-d8407b4d9dda",
  },
  {
    businessPhones: [],
    displayName: "Don Holding -",
    givenName: null,
    jobTitle: null,
    mail: "donholding@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "donholding@evergreenbrands.com",
    id: "5220d6e9-84fd-4f70-b44e-f028840e890a",
  },
  {
    businessPhones: [],
    displayName: "Elias Dangar - SM 2026",
    givenName: "Elias",
    jobTitle: "Senior Business Development Professional",
    mail: "EliDan@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Dangar",
    userPrincipalName:
      "EliDan_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "b13bc313-c0d1-4958-8eaf-92595b628918",
  },
  {
    businessPhones: [],
    displayName: "Elizabeth Ela - SM 2006",
    givenName: "Elizabeth",
    jobTitle: "Customer Experience & Administrative Assistant",
    mail: "Elizabeth.Ela@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Ela",
    userPrincipalName:
      "Elizabeth.Ela_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "e937e8a1-d7a4-4be0-92e1-36188a7eb393",
  },
  {
    businessPhones: [],
    displayName: "Eljing Villanca",
    givenName: null,
    jobTitle: "Assistant Community Association Manager",
    mail: "Eljing.Villanca@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: null,
    userPrincipalName:
      "Eljing.Villanca_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "20609196-6690-44d4-92f6-2f401543dadd",
  },
  {
    businessPhones: ["(206) 610-0080"],
    displayName: "Eric Michelson - SM 2026",
    givenName: "Eric",
    jobTitle: "Project Manager",
    mail: "EriMic@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Michelson",
    userPrincipalName:
      "EriMic_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "b1c6889e-50bd-4f48-a903-3d6b26870b4e",
  },
  {
    businessPhones: ["(713) 280-6613"],
    displayName: "Erynn Pyles",
    givenName: "Erynn",
    jobTitle: "Vice President of Operations",
    mail: "EryPyl@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Home",
    preferredLanguage: "en-US",
    surname: "Pyles",
    userPrincipalName:
      "EryPyl_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "c89c3dfc-8fa9-4b93-841f-22920d1d67fd",
  },
  {
    businessPhones: ["(206) 804-1250"],
    displayName: "Ethan Hoshino - SM 2025",
    givenName: "Ethan",
    jobTitle: "Human Resources Business Partner",
    mail: "Ethan.Hoshino@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Hoshino",
    userPrincipalName: "Ethan.Hoshino@evergreenbrands.com",
    id: "97128e8c-d686-4912-99db-8b45917afbb5",
  },
  {
    businessPhones: ["(856) 930-7700"],
    displayName: "Glenn Reed - SM 2025",
    givenName: "Glenn",
    jobTitle: "Consultant",
    mail: "Glenn.Reed@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Home",
    preferredLanguage: null,
    surname: "Reed",
    userPrincipalName: "Glenn.Reed@evergreenbrands.com",
    id: "43893f68-1c69-4512-a583-a80de1fe5e11",
  },
  {
    businessPhones: [],
    displayName: "Griffin Price -",
    givenName: "Griffin",
    jobTitle: null,
    mail: "Griffin.Price@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Price",
    userPrincipalName: "Griffin.Price@evergreenbrands.com",
    id: "f909a944-e989-4735-9227-958d1174cedf",
  },
  {
    businessPhones: ["(206) 853-0120"],
    displayName: "Griffin Price",
    givenName: "Griffin",
    jobTitle: "Landscape Designs Consultant Trainee",
    mail: "GriffinP@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Price",
    userPrincipalName:
      "GriffinP_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "d14024a8-6822-49cd-bb89-7ecc18ddde55",
  },
  {
    businessPhones: [],
    displayName: "Hailey Heilman - SM 2026",
    givenName: "Hailey",
    jobTitle: "Sourcing Coordinator",
    mail: "HaiHei@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Heilman",
    userPrincipalName:
      "HaiHei_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "4d23d329-c4ed-438a-85aa-2f21d0582fe4",
  },
  {
    businessPhones: ["(360) 316-4235"],
    displayName: "Haley Dobbs",
    givenName: "Haley",
    jobTitle: "Team Lead",
    mail: "HalDob@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "Dobbs",
    userPrincipalName:
      "HalDob_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "a291b1cf-f855-4912-92f6-4cd92dacf82e",
  },
  {
    businessPhones: ["206-843-1697"],
    displayName: "Haylie Abdullah",
    givenName: "Haylie",
    jobTitle: "Sourcing Manager ",
    mail: "HayAbd@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "Abdullah",
    userPrincipalName:
      "HayAbd_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "1046ad94-bd9e-4458-8146-837037b532c7",
  },
  {
    businessPhones: [],
    displayName: "EB Help Desk -",
    givenName: null,
    jobTitle: null,
    mail: "helpdesk@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "helpdesk@evergreenbrands.com",
    id: "9e5cad78-3148-4249-920e-9f94e7497f55",
  },
  {
    businessPhones: [],
    displayName: "Hercelyn Conquilla - SM 2026",
    givenName: "Hercelyn",
    jobTitle: "Sales Administrative Assistant",
    mail: "HerCon@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Conquilla",
    userPrincipalName:
      "HerCon_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "7210964f-e11d-473f-9147-e45f70d21a1b",
  },
  {
    businessPhones: [],
    displayName: "HR -",
    givenName: null,
    jobTitle: null,
    mail: "hr@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "hr@evergreenbrands.com",
    id: "fbcb99e9-142c-415a-93e8-4837f5129bde",
  },
  {
    businessPhones: [],
    displayName: "Ian McGuire - SM 2026",
    givenName: "Ian",
    jobTitle: "Accounting Specialist",
    mail: "IanMcG@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "McGuire",
    userPrincipalName:
      "IanMcG_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "9768c086-5852-4d5b-9222-e4b6d73c2c9a",
  },
  {
    businessPhones: [],
    displayName: "Info Lawn Tech",
    givenName: "Info",
    jobTitle: null,
    mail: null,
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Lawn Tech",
    userPrincipalName: "info@Lawn-tech.net",
    id: "008b4d7b-8a9d-4bc9-ba84-aec5c7c979c6",
  },
  {
    businessPhones: [],
    displayName: "info - SM",
    givenName: "info - mBridge",
    jobTitle: null,
    mail: "info@mbridge.global",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "info@mbridge.global",
    id: "39c68d11-7da2-40c1-866d-25c1b02dc115",
  },
  {
    businessPhones: ["206-804-1205"],
    displayName: "Isaac Arneson",
    givenName: "Isaac",
    jobTitle: null,
    mail: "Isaac.Arneson@evergreenbrands.com",
    mobilePhone: "360-522-3003",
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Arneson",
    userPrincipalName: "Isaac.Arneson@evergreenbrands.com",
    id: "38875a2a-bf5e-4742-a916-432abc4c9dca",
  },
  {
    businessPhones: [],
    displayName: "Isaac Arneson",
    givenName: "Isaac",
    jobTitle: "President",
    mail: "IsaacA@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Arneson",
    userPrincipalName:
      "IsaacA_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "7f228d6a-f0e9-455d-9849-0c41526d4dd7",
  },
  {
    businessPhones: [],
    displayName: "Jacob Boyd",
    givenName: "Jacob",
    jobTitle: "Project Manager",
    mail: "JacobB@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Boyd",
    userPrincipalName:
      "JacobB_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "a49dabd5-2a51-4545-8ae2-2ba32a61df32",
  },
  {
    businessPhones: ["(617) 388-2006"],
    displayName: "James Calo",
    givenName: "James",
    jobTitle: "Field Branch Manager ",
    mail: "JamCal@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Operations MA",
    preferredLanguage: "en-US",
    surname: "Calo",
    userPrincipalName:
      "JamCal_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "09d02f86-73a7-4c8b-b4f1-d0ab8d1eb186",
  },
  {
    businessPhones: [],
    displayName: "Jason Chaidez",
    givenName: "Jason",
    jobTitle: "Senior Accountant",
    mail: "Jason.Chaidez@condoshield.org",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Chaidez",
    userPrincipalName:
      "Jason.Chaidez_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8bf60ccb-ce24-4677-9f7e-58aaf1e1863c",
  },
  {
    businessPhones: ["(215) 915-9600"],
    displayName: "Jason Ostrander - SM 2026",
    givenName: "Jason",
    jobTitle: "Vice President of Operations",
    mail: "JasOst@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Ostrander",
    userPrincipalName:
      "JasOst_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "a90e7587-f33d-40d1-80fd-a463259f27d4",
  },
  {
    businessPhones: [],
    displayName: "Jennifer Hulbert - SM 2025",
    givenName: "Jennifer",
    jobTitle: "Sourcing Coordinator",
    mail: "JenHul@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Hulbert",
    userPrincipalName:
      "JenHul_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2dcda4f0-626c-41c7-a038-ea639c176490",
  },
  {
    businessPhones: ["(425) 981-6956"],
    displayName: "Jessica Ward",
    givenName: "Jessica",
    jobTitle: "Account Coordinator ",
    mail: "JesWar@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Home",
    preferredLanguage: "en-US",
    surname: "Ward",
    userPrincipalName:
      "JesWar_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "1e821bbf-666d-4d41-a842-ee23248c630e",
  },
  {
    businessPhones: ["(206) 804-0350"],
    displayName: "Jim Wescott",
    givenName: "Jim",
    jobTitle: "Vice President, Technology",
    mail: "jim.wescott@evergreenbrands.com",
    mobilePhone: "(425) 577-1086",
    officeLocation: "Everett",
    preferredLanguage: "en-US",
    surname: "Wescott",
    userPrincipalName: "jim.wescott@evergreenbrands.com",
    id: "644d46f3-f507-41ef-8478-48c0edbeb4b6",
  },
  {
    businessPhones: [],
    displayName: "Jim Wescott - GPI",
    givenName: "Jim",
    jobTitle: null,
    mail: "Jim.Wescott@getplowedindustries.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Wescott - GPI",
    userPrincipalName: "Jim.Wescott@getplowedindustries.com",
    id: "978ad0ff-33ef-456e-a218-4075b0e38ab5",
  },
  {
    businessPhones: ["206-804-0350"],
    displayName: "Jim Wescott - CS",
    givenName: "Jim",
    jobTitle: "Vice President, Technology",
    mail: "jim@condoshield.org",
    mobilePhone: null,
    officeLocation: "Everett",
    preferredLanguage: "en-US",
    surname: "Wescott",
    userPrincipalName:
      "jim_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "606e9788-bd81-4f71-bf7d-f4f205a101e7",
  },
  {
    businessPhones: ["2068040350"],
    displayName: "Jim Wescott - SLD",
    givenName: "Jim",
    jobTitle: null,
    mail: "jimW@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en",
    surname: "Wescott",
    userPrincipalName:
      "jimW_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "d6e548aa-1d72-4a08-b719-57e56a277284",
  },
  {
    businessPhones: ["206-804-0350"],
    displayName: "Jim Wescott -",
    givenName: "Jim",
    jobTitle: "Vice President Technology",
    mail: "JimWes@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en",
    surname: "Wescott",
    userPrincipalName:
      "JimWes_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "b9b5ea99-0ec6-430f-b9b2-ee66c735d761",
  },
  {
    businessPhones: ["(617) 777-1421"],
    displayName: "John Dubil",
    givenName: "John",
    jobTitle: "Regional Field Manager- IL Market ",
    mail: "JohDub@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Dubil",
    userPrincipalName:
      "JohDub_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "c5d8ca66-0069-4f43-b53c-5b19294f4d71",
  },
  {
    businessPhones: ["(206) 750-6830"],
    displayName: "Jonah Srb",
    givenName: "Jonah",
    jobTitle: "Sales Manager",
    mail: "Jonah.Srb@evergreenbrands.com",
    mobilePhone: "206-973-9992",
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Srb",
    userPrincipalName: "Jonah.Srb@evergreenbrands.com",
    id: "d951091f-14a3-44a2-a7c6-bf7f9e2e1176",
  },
  {
    businessPhones: ["206-750-6833"],
    displayName: "Jonathan McQuade -",
    givenName: "Jonathan",
    jobTitle: "General Counsel",
    mail: "Jonathan.McQuade@evergreenbrands.com",
    mobilePhone: "206-913-7174",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "McQuade",
    userPrincipalName: "Jonathan.McQuade@evergreenbrands.com",
    id: "9dfd2365-68d5-42e2-9806-b27fee09b0f0",
  },
  {
    businessPhones: ["(425) 981-6965"],
    displayName: "Jonathan Bond",
    givenName: "Jonathan",
    jobTitle: "Client Account Specialist",
    mail: "JonBon@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Bond",
    userPrincipalName:
      "JonBon_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "b5be0bb3-91fa-4dcc-b86c-331a33308509",
  },
  {
    businessPhones: ["(425) 981-6958"],
    displayName: "Jon Franklin",
    givenName: "Jon",
    jobTitle: "Sourcing Coordinator",
    mail: "JonFra@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Franklin",
    userPrincipalName:
      "JonFra_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "400882bc-323a-418f-bfbb-6cd75bd56cf0",
  },
  {
    businessPhones: ["(206) 750-6830"],
    displayName: "Jonah Srb",
    givenName: "Jonah",
    jobTitle: "Sales Manager",
    mail: "JonSrb@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Srb",
    userPrincipalName:
      "JonSrb_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3a0b5941-4203-4db8-a647-a995cbd26a98",
  },
  {
    businessPhones: [],
    displayName: "Jorge Gonzalez",
    givenName: "Jorge",
    jobTitle: "Crew Member ",
    mail: "JorGon@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Gonzalez",
    userPrincipalName:
      "JorGon_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "1dd9d9eb-3985-489d-b7ba-0f406c324aa1",
  },
  {
    businessPhones: [],
    displayName: "Joseph Toups - SM -23",
    givenName: "Joseph",
    jobTitle: "Associate Counsel",
    mail: "Joseph.Toups@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Toups",
    userPrincipalName: "Joseph.Toups@evergreenbrands.com",
    id: "9bb7cc24-5df4-43ec-8c41-7a76559f68be",
  },
  {
    businessPhones: [],
    displayName: "jim Admin -",
    givenName: "jim",
    jobTitle: null,
    mail: "JW@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Admin",
    userPrincipalName: "JW@evergreenbrands.com",
    id: "d9f74500-72e5-4162-8296-6e493af20674",
  },
  {
    businessPhones: ["(425) 981-6997"],
    displayName: "Kaitlyn Goins",
    givenName: "Kaitlyn",
    jobTitle: "Sourcing Coordinator",
    mail: "KaiGoi@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Goins",
    userPrincipalName:
      "KaiGoi_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2585fd82-feb8-4375-8668-8e731ced6b75",
  },
  {
    businessPhones: [],
    displayName: "Kama Stuart",
    givenName: "Kama",
    jobTitle: "Sr. Account Specialist",
    mail: "KamStu@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Stuart",
    userPrincipalName:
      "KamStu_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "46703549-c580-4ab1-9ca2-7b6f8be42003",
  },
  {
    businessPhones: ["(425) 996-3504"],
    displayName: "Karen Houret",
    givenName: "Karen",
    jobTitle: "Sourcing Specialist",
    mail: "KarHou@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Houret",
    userPrincipalName:
      "KarHou_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "d913b4bf-8c34-4930-9bd2-8c365a44766f",
  },
  {
    businessPhones: ["206-941-6846"],
    displayName: "Kayn Mcintosh",
    givenName: "Kayn",
    jobTitle: "Association Manager and Site Inspector",
    mail: "Kayn.McIntosh@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "McIntosh",
    userPrincipalName:
      "Kayn.McIntosh_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8429c0d5-2771-491a-830d-96dc2678a709",
  },
  {
    businessPhones: [],
    displayName: "Kenneth Brouillette",
    givenName: "Kenneth",
    jobTitle: "Lawn care crew member ",
    mail: "KenBro@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Brouillette",
    userPrincipalName:
      "KenBro_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "7a2cb2ad-7cfa-46fd-9700-e0f32a0ba2ce",
  },
  {
    businessPhones: [],
    displayName: "Kevin Kok - SM 2026",
    givenName: "Kevin",
    jobTitle: "Project Manager – Capital & Government Projects",
    mail: "KevKok@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Kok",
    userPrincipalName:
      "KevKok_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "56e9b077-4c87-43ba-bed5-b9b920bc7d44",
  },
  {
    businessPhones: [],
    displayName: "Kevin McCollum",
    givenName: "Kevin",
    jobTitle: "On Demand Technician ",
    mail: "KevMcC@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "McCollum",
    userPrincipalName:
      "KevMcC_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "41c250e0-c3c4-4a37-9aa0-07139eb55560",
  },
  {
    businessPhones: ["206-804-1202"],
    displayName: "Larry Hyatt - SM 2024",
    givenName: "Larry",
    jobTitle: "Senior Vice President, Operations",
    mail: "larry.hyatt@evergreenbrands.com",
    mobilePhone: "(646)483-5048",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Hyatt",
    userPrincipalName: "larry.hyatt@evergreenbrands.com",
    id: "52dcb4dd-0dff-450f-bb50-73a2450ef60e",
  },
  {
    businessPhones: [],
    displayName: "Larry Holdiong -",
    givenName: null,
    jobTitle: null,
    mail: "larryholdiong@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "larryholdiong@evergreenbrands.com",
    id: "d670d8bb-1ce9-40f3-8ca0-a812b69c159b",
  },
  {
    businessPhones: ["(206)-610-2373"],
    displayName: "Laura Betancourt",
    givenName: "Laura",
    jobTitle: "Senior Account Manager",
    mail: "LauBet@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Betancourt",
    userPrincipalName:
      "LauBet_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "052a7263-033d-41fa-8c5a-1236d0455352",
  },
  {
    businessPhones: [],
    displayName: "legal -",
    givenName: null,
    jobTitle: null,
    mail: "legal@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "legal@evergreenbrands.com",
    id: "b2076251-a27e-47ea-8fbd-3bd619624bd3",
  },
  {
    businessPhones: ["206-807-0583"],
    displayName: "Lisa Pilkington",
    givenName: "Lisa",
    jobTitle: "Landscaping Foreman - Commercial Operations",
    mail: "LisPil@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Pilkington",
    userPrincipalName:
      "LisPil_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "683da876-ff1a-4b08-83ad-802fd7deecce",
  },
  {
    businessPhones: [],
    displayName: "Logan Ross",
    givenName: "Logan",
    jobTitle: "Project Manager",
    mail: "LoganR@seattlelandscapedesigns.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Ross",
    userPrincipalName:
      "LoganR_seattlelandscapedesigns.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "70786bd7-3dc6-4874-b81e-07105d749b0a",
  },
  {
    businessPhones: [],
    displayName: "Madison Peters",
    givenName: "Madison",
    jobTitle: "Account Coordinator ",
    mail: "MadPet@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Peters",
    userPrincipalName:
      "MadPet_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8b0d266b-6672-4c55-8cb8-4c16bea51dfa",
  },
  {
    businessPhones: ["(206) 591-1281"],
    displayName: "Tina Roth",
    givenName: "Tina",
    jobTitle: "Executive Assistant",
    mail: "TinRot@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Roth",
    userPrincipalName:
      "TinRot_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "2a352402-66dc-4b4e-941d-be37d0dc27af",
  },
  {
    businessPhones: [],
    displayName: "Matthew Westhoven",
    givenName: "Matthew",
    jobTitle: "Prologis Site Manager",
    mail: "MatWes@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Westhoven",
    userPrincipalName:
      "MatWes_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "23cb81eb-6087-4c0d-842b-e4305c630e47",
  },
  {
    businessPhones: [],
    displayName: "Michael Ramirez",
    givenName: "Michael",
    jobTitle: "Lawn foreman ",
    mail: "MicRam@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Ramirez",
    userPrincipalName:
      "MicRam_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "03148966-0eeb-40db-ac00-4eb647061b0c",
  },
  {
    businessPhones: [],
    displayName: "Milissa Meyers - SM 2024",
    givenName: "Milissa",
    jobTitle: null,
    mail: "Milissa.Meyers@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Meyers",
    userPrincipalName: "Milissa.Meyers@evergreenbrands.com",
    id: "7881fb68-22a8-4c52-ab3a-f9ebd521dc7f",
  },
  {
    businessPhones: ["(206) 591-4312"],
    displayName: "Missy Koshman",
    givenName: "Missy",
    jobTitle: "Senior Coordinator",
    mail: "MisKos@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Koshman",
    userPrincipalName:
      "MisKos_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "0ff69805-7d2a-4d0c-ad7d-1ef46e64eec4",
  },
  {
    businessPhones: [],
    displayName: "Myles Jackson",
    givenName: "Myles",
    jobTitle: "Lawn Crew member ",
    mail: "MylJac@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Jackson",
    userPrincipalName:
      "MylJac_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "f0b04127-2467-4f84-b427-acb76351d897",
  },
  {
    businessPhones: [],
    displayName: "New Hires",
    givenName: null,
    jobTitle: null,
    mail: "newhires@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "newhires@evergreenbrands.com",
    id: "c42a15c5-e16a-4c8c-a682-49231cdda75c",
  },
  {
    businessPhones: [],
    displayName: "No Reply",
    givenName: "No",
    jobTitle: null,
    mail: "no-reply@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Reply",
    userPrincipalName: "no-reply@evergreenbrands.com",
    id: "a9f29e14-07b1-4a33-be7a-7ccb986d5025",
  },
  {
    businessPhones: [],
    displayName: "Paul Comer - SM 2025",
    givenName: "Paul",
    jobTitle: null,
    mail: "Paul.Comer@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Comer",
    userPrincipalName: "Paul.Comer@evergreenbrands.com",
    id: "c98dc952-816d-45af-9db3-7ef4c127ec80",
  },
  {
    businessPhones: ["(713) 940-1297"],
    displayName: "Payton O'Bryan SM - 2026",
    givenName: "Payton",
    jobTitle: "Sales Representative- Subcontractor Services",
    mail: "PayOBr@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "O'Bryan",
    userPrincipalName:
      "PayOBr_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3d3a2cb3-0913-4ab6-9695-dbded2a58fe6",
  },
  {
    businessPhones: [],
    displayName: "Ralph Helm",
    givenName: "Ralph",
    jobTitle: "Creative Director",
    mail: "Ralph.Helm@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Helm",
    userPrincipalName: "Ralph.Helm@evergreenbrands.com",
    id: "f4e50d65-daad-4472-bacc-59ba5ff04ec0",
  },
  {
    businessPhones: [],
    displayName: "Rose Anne Rojas",
    givenName: "Rose Anne",
    jobTitle: "Accountant",
    mail: "RoseAnne.Rojas@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Rojas",
    userPrincipalName:
      "RoseAnne.Rojas_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "e6ee4ff7-253a-4745-838d-66a18661084e",
  },
  {
    businessPhones: [],
    displayName: "Sam Smith",
    givenName: "Sam",
    jobTitle: null,
    mail: null,
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Smith",
    userPrincipalName: "Sam.Smith@evergreenbrands.com",
    id: "45f747c6-11df-4669-b4a6-ded328f23e3f",
  },
  {
    businessPhones: ["(713) 757-2494"],
    displayName: "Samantha Smith",
    givenName: "Samantha",
    jobTitle: "Controller",
    mail: "SamSmi@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Smith",
    userPrincipalName:
      "SamSmi_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "02bad145-4ca0-4e00-9665-f4155b100cf0",
  },
  {
    businessPhones: [],
    displayName: "Santa Jack -",
    givenName: null,
    jobTitle: null,
    mail: "santajack@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "santajack@evergreenbrands.com",
    id: "01e2f06b-7f04-4f46-bf7b-2f8d5f5d50bc",
  },
  {
    businessPhones: [],
    displayName: "Sarah Carter",
    givenName: "Sarah",
    jobTitle: "Lead Software Developer",
    mail: "Sarah.Carter@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Carter",
    userPrincipalName: "Sarah.Carter@evergreenbrands.com",
    id: "92da22b9-3f87-40b0-a3c4-5d205861d6df",
  },
  {
    businessPhones: [],
    displayName: "Scott Calentine - SM 2025",
    givenName: "Scott",
    jobTitle: null,
    mail: "scott@Honey4hope.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Calentine",
    userPrincipalName: "scott@Honey4hope.org",
    id: "e86778f8-4111-4840-aa44-985fcb845b51",
  },
  {
    businessPhones: [],
    displayName: "Shad Lawn Tech",
    givenName: null,
    jobTitle: null,
    mail: "shad@Lawn-tech.net",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "shad@evergreenbrands.com",
    id: "873a5d0c-b6eb-4756-a89c-17818bc4d0e4",
  },
  {
    businessPhones: ["(206) 828-0067"],
    displayName: "Shelly Fuller",
    givenName: "Shelly",
    jobTitle: "President",
    mail: "sheful@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Fuller",
    userPrincipalName:
      "sheful_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "4329f5f8-8562-4a45-b00a-d189cdb95b46",
  },
  {
    businessPhones: [],
    displayName: "Shelly Fuller",
    givenName: "Shelly",
    jobTitle: null,
    mail: "Shelly.Fuller@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Fuller",
    userPrincipalName: "Shelly.Fuller@evergreenbrands.com",
    id: "2bcb0e5c-23b2-464e-9402-937c217701d0",
  },
  {
    businessPhones: [],
    displayName: "Sheri Fleck - SM 2024",
    givenName: "Sheri",
    jobTitle: null,
    mail: "Sheri.Fleck@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Fleck",
    userPrincipalName: "Sheri.Fleck@evergreenbrands.com",
    id: "b8973224-2b2b-41b8-8860-f95527051070",
  },
  {
    businessPhones: ["(425) 981-6925"],
    displayName: "Sierra Keith",
    givenName: "Sierra",
    jobTitle: "Sourcing Coordinator",
    mail: "SieKei@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Keith",
    userPrincipalName:
      "SieKei_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "0868b2e3-eb85-4634-b388-baf6910ac459",
  },
  {
    businessPhones: [],
    displayName: "Software Feedback -",
    givenName: null,
    jobTitle: null,
    mail: "softwarefeedback@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "softwarefeedback@evergreenbrands.com",
    id: "9ca50720-8a47-407f-b9e8-33cb72af762a",
  },
  {
    businessPhones: [],
    displayName: "Sophia Cerimele",
    givenName: "Sophia",
    jobTitle: "Account Coordinator ",
    mail: "SopCer@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Cerimele",
    userPrincipalName:
      "SopCer_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8807a19c-94ef-491e-ab33-59b4f86d8e56",
  },
  {
    businessPhones: ["(206) 804-1249"],
    displayName: "Stephen Houret",
    givenName: "Stephen",
    jobTitle: "Vice President Operations - Integrated Services",
    mail: "stehou@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Monroe",
    preferredLanguage: "en-US",
    surname: "Houret",
    userPrincipalName:
      "stehou_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "e4ad855b-6860-4687-851b-bb253867f246",
  },
  {
    businessPhones: [],
    displayName: "Stephen Houret",
    givenName: "Stephen",
    jobTitle: null,
    mail: "Stephen.Houret@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Houret",
    userPrincipalName: "Stephen.Houret@evergreenbrands.com",
    id: "6f8aadf7-3955-430f-92b6-e5caaa0980c5",
  },
  {
    businessPhones: [],
    displayName: "Teila Velock",
    givenName: "Teila",
    jobTitle: "Accounting Assistant",
    mail: "TeiVel@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Velock",
    userPrincipalName:
      "TeiVel_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "4b511e0e-b119-4d5a-99fd-c278fccf4470",
  },
  {
    businessPhones: [],
    displayName: "The Loft",
    givenName: null,
    jobTitle: null,
    mail: "TheLoft@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: "Barn upstars",
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "TheLoft@evergreenbrands.com",
    id: "df9b8d93-026d-40af-a8f3-0b422ac9dd5c",
  },
  {
    businessPhones: ["(206)823-6433"],
    displayName: "Theresa Nelson - SM 2025",
    givenName: "Theresa",
    jobTitle: "Controller",
    mail: "Theresa.Nelson@evergreenbrands.com",
    mobilePhone: "425-280-1025",
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Nelson",
    userPrincipalName: "Theresa.Nelson@evergreenbrands.com",
    id: "8ea05e83-ad2d-4186-87ef-50caab626150",
  },
  {
    businessPhones: ["(206) 591-1281"],
    displayName: "Tina Roth",
    givenName: "Tina",
    jobTitle: "Executive Assistant",
    mail: "Tina.Roth@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Roth",
    userPrincipalName: "Tina.Roth@evergreenbrands.com",
    id: "d64006d2-b7a6-4648-902a-16de36a42632",
  },
  {
    businessPhones: ["206-804-1205"],
    displayName: "Todd Chapman - SM 2024",
    givenName: "Todd",
    jobTitle: "Vice President Human Resources",
    mail: "Todd.Chapman@evergreenbrands.com",
    mobilePhone: "425-772-4970",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Chapman",
    userPrincipalName: "Todd.Chapman@evergreenbrands.com",
    id: "568c12be-112c-48c7-b205-2d0f6917936b",
  },
  {
    businessPhones: ["206-804-1205"],
    displayName: "Todd Chapman - SM 2025",
    givenName: "Todd",
    jobTitle: "VP of Human Resources ",
    mail: "Todd@wcgpro.com",
    mobilePhone: "206-804-1205",
    officeLocation: null,
    preferredLanguage: null,
    surname: "Chapman",
    userPrincipalName: "Todd@wcgpro.com",
    id: "759f6b1d-4945-4b42-81a0-b8cea339cf2a",
  },
  {
    businessPhones: [],
    displayName: "Todd Holding -",
    givenName: null,
    jobTitle: null,
    mail: "toddholding@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "toddholding@evergreenbrands.com",
    id: "f28ad69d-6c51-4ce1-8b4f-abc7918701a9",
  },
  {
    businessPhones: [],
    displayName: "Tyler Black",
    givenName: "Tyler",
    jobTitle: "Junior Accountant",
    mail: "TylBla@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "WFH",
    preferredLanguage: "en-US",
    surname: "Black",
    userPrincipalName:
      "TylBla_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "5542a8dc-06b5-4590-894d-418136835729",
  },
  {
    businessPhones: [],
    displayName: "Tyler Black",
    givenName: "Tyler",
    jobTitle: null,
    mail: null,
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Black",
    userPrincipalName: "Tyler.Black@evergreenbrands.com",
    id: "a4019132-6f4e-4b30-894a-0dc5ddf90a71",
  },
  {
    businessPhones: [],
    displayName: "Uziel Morales - SM 23",
    givenName: "Uziel",
    jobTitle: "Dev",
    mail: "Uziel.Morales@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: "Morales",
    userPrincipalName: "Uziel.Morales@evergreenbrands.com",
    id: "8d1902b2-2b2c-4e81-87ec-3efa6f9c82fc",
  },
  {
    businessPhones: ["(425) 981-6963"],
    displayName: "Valerie Haworth",
    givenName: "Valerie",
    jobTitle: "Sourcing Coordinator",
    mail: "ValHaw@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Haworth",
    userPrincipalName:
      "ValHaw_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "8b70f61b-f7da-4c8d-a852-2b93c23c38f7",
  },
  {
    businessPhones: ["206-804-0826"],
    displayName: "Vince Ortiz - SM 2024",
    givenName: "Vince",
    jobTitle: "Senior Vice President, Business Development",
    mail: "Vince.Ortiz@evergreenbrands.com",
    mobilePhone: "206-557-0147",
    officeLocation: "Everett",
    preferredLanguage: null,
    surname: "Ortiz",
    userPrincipalName: "Vince.Ortiz@evergreenbrands.com",
    id: "b3236abe-285e-49d5-865c-3aca1428c06b",
  },
  {
    businessPhones: [],
    displayName: "Vince Ortiz",
    givenName: "Vince",
    jobTitle: null,
    mail: "VinceO@emeraldcityasphalt.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Ortiz",
    userPrincipalName:
      "VinceO_emeraldcityasphalt.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "832d5244-8e64-4b29-b5c4-157c86146525",
  },
  {
    businessPhones: ["(425) 310-8395"],
    displayName: "Virginia Nelson - SM 2026",
    givenName: "Virginia",
    jobTitle: "Business Development Representative",
    mail: "VirNel@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Nelson",
    userPrincipalName:
      "VirNel_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "a7de1a84-f64e-4a49-ac59-097c5657e097",
  },
  {
    businessPhones: [],
    displayName: "Vince Holding -",
    givenName: null,
    jobTitle: null,
    mail: "voholding@evergreenbrands.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: null,
    surname: null,
    userPrincipalName: "voholding@evergreenbrands.com",
    id: "4f154178-2ec7-406b-8405-607c171eca16",
  },
  {
    businessPhones: ["425-245-4323"],
    displayName: "Yan Wang",
    givenName: "Yan",
    jobTitle: "Sr. Accountant",
    mail: "Yan.Wang@evergreenbrands.com",
    mobilePhone: "202-615-4865",
    officeLocation: "Monroe",
    preferredLanguage: null,
    surname: "Wang",
    userPrincipalName: "Yan.Wang@evergreenbrands.com",
    id: "50fbde53-e46c-430f-afd8-cfb1fcf96abc",
  },
  {
    businessPhones: ["(832) 617-0872"],
    displayName: "Yasmine Hernandez",
    givenName: "Yasmine",
    jobTitle: "Sourcing Coordinator",
    mail: "YasHer@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Hernandez",
    userPrincipalName:
      "YasHer_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "42ad79d4-28ad-489e-856e-84d92e3e64d7",
  },
  {
    businessPhones: ["(617) 848-9243"],
    displayName: "Zach Jones",
    givenName: "Zach",
    jobTitle: "Sourcing Coordinator",
    mail: "ZacJon@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: "Remote",
    preferredLanguage: "en-US",
    surname: "Jones",
    userPrincipalName:
      "ZacJon_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "3d409c8c-97f7-4211-854c-962652f42520",
  },
  {
    businessPhones: [],
    displayName: "Zander W",
    givenName: "Zander",
    jobTitle: null,
    mail: "zander@condoshield.org",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "W",
    userPrincipalName:
      "zander_condoshield.org#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "66450d0a-c925-4c3b-90fa-85bc1c32e92f",
  },
  {
    businessPhones: [],
    displayName: "Zeshoun Prince",
    givenName: "Zeshoun",
    jobTitle: "Laborer",
    mail: "ZesPri@nationalfacilitycontractors.com",
    mobilePhone: null,
    officeLocation: null,
    preferredLanguage: "en-US",
    surname: "Prince",
    userPrincipalName:
      "ZesPri_nationalfacilitycontractors.com#EXT#@EvergreenBrandsLLC.onmicrosoft.com",
    id: "890cc384-b0ad-4404-b870-74810af7ffc2",
  },
];

export default existingEmployees;
